---
# ONNX VAD Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onnx-vad
  namespace: loom-dev
  labels:
    app: onnx-vad
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onnx-vad
  template:
    metadata:
      labels:
        app: onnx-vad
        component: ai-processing
    spec:
      containers:
      - name: onnx-vad
        image: loom/onnx-vad:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: VAD_MODEL_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30  # Allow 5 minutes for startup (10s * 30)
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: onnx-vad
  namespace: loom-dev
  labels:
    app: onnx-vad
spec:
  selector:
    app: onnx-vad
  ports:
  - port: 8001
    targetPort: 8001
    name: http

---
# MiniCPM Vision Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minicpm-vision
  namespace: loom-dev
  labels:
    app: minicpm-vision
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minicpm-vision
  template:
    metadata:
      labels:
        app: minicpm-vision
        component: ai-processing
    spec:
      containers:
      - name: minicpm-vision
        image: loom/minicpm-vision:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: VISION_MODEL_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "4000m"
            memory: "16Gi"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 40  # Allow 10 minutes for startup (15s * 40)
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: minicpm-vision
  namespace: loom-dev
  labels:
    app: minicpm-vision
spec:
  selector:
    app: minicpm-vision
  ports:
  - port: 8000
    targetPort: 8000
    name: http

---
# ONNX ASR Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onnx-asr
  namespace: loom-dev
  labels:
    app: onnx-asr
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onnx-asr
  template:
    metadata:
      labels:
        app: onnx-asr
        component: ai-processing
    spec:
      containers:
      - name: onnx-asr
        image: loom/onnx-asr:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8002
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: ASR_MODEL_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 36  # Allow 6 minutes for startup (10s * 36)
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: onnx-asr
  namespace: loom-dev
  labels:
    app: onnx-asr
spec:
  selector:
    app: onnx-asr
  ports:
  - port: 8002
    targetPort: 8002
    name: http
