---
# Silero VAD Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silero-vad
  namespace: loom-dev
  labels:
    app: silero-vad
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: silero-vad
  template:
    metadata:
      labels:
        app: silero-vad
        component: ai-processing
    spec:
      containers:
      - name: silero-vad
        image: loom/silero-vad:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: VAD_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: silero-vad
  namespace: loom-dev
  labels:
    app: silero-vad
spec:
  selector:
    app: silero-vad
  ports:
  - port: 8000
    targetPort: 8000
    name: http

---
# MiniCPM Vision Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minicpm-vision
  namespace: loom-dev
  labels:
    app: minicpm-vision
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minicpm-vision
  template:
    metadata:
      labels:
        app: minicpm-vision
        component: ai-processing
    spec:
      containers:
      - name: minicpm-vision
        image: loom/minicpm-vision:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: VISION_MODEL_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "4000m"
            memory: "16Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 120  # Model loading takes time
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: minicpm-vision
  namespace: loom-dev
  labels:
    app: minicpm-vision
spec:
  selector:
    app: minicpm-vision
  ports:
  - port: 8000
    targetPort: 8000
    name: http

---
# Parakeet TDT ASR Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parakeet-tdt
  namespace: loom-dev
  labels:
    app: parakeet-tdt
    component: ai-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parakeet-tdt
  template:
    metadata:
      labels:
        app: parakeet-tdt
        component: ai-processing
    spec:
      containers:
      - name: parakeet-tdt
        image: loom/parakeet-tdt:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        - name: ASR_MODEL_DEVICE
          value: "cpu"  # Change to "cuda" if GPU available
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 90  # Model loading takes time
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: parakeet-tdt
  namespace: loom-dev
  labels:
    app: parakeet-tdt
spec:
  selector:
    app: parakeet-tdt
  ports:
  - port: 8000
    targetPort: 8000
    name: http