---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hackernews-fetcher
  namespace: loom-dev
  labels:
    app: hackernews-fetcher
    component: data-ingestion
spec:
  # Run every 15 minutes
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: hackernews-fetcher
            component: data-ingestion
        spec:
          restartPolicy: Never
          containers:
          - name: hackernews-fetcher
            image: loom/hackernews-fetcher:latest
            imagePullPolicy: Never
            env:
            - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-infra-chart:9092"
            - name: LOOM_LOG_LEVEL
              value: "INFO"
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: email-fetcher
  namespace: loom-dev
  labels:
    app: email-fetcher
    component: data-ingestion
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: email-fetcher
            component: data-ingestion
        spec:
          restartPolicy: Never
          containers:
          - name: email-fetcher
            image: loom/email-fetcher:latest
            imagePullPolicy: Never
            env:
            - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-infra-chart:9092"
            - name: LOOM_LOG_LEVEL
              value: "INFO"
            - name: EMAIL_IMAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: imap-server
                  optional: true
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: username
                  optional: true
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: password
                  optional: true
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "300m"
                memory: "256Mi"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: calendar-fetcher
  namespace: loom-dev
  labels:
    app: calendar-fetcher
    component: data-ingestion
spec:
  # Run every 10 minutes
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: calendar-fetcher
            component: data-ingestion
        spec:
          restartPolicy: Never
          containers:
          - name: calendar-fetcher
            image: loom/calendar-fetcher:latest
            imagePullPolicy: Never
            env:
            - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-infra-chart:9092"
            - name: LOOM_LOG_LEVEL
              value: "INFO"
            - name: CALENDAR_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: calendar-credentials
                  key: client-id
                  optional: true
            - name: CALENDAR_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: calendar-credentials
                  key: client-secret
                  optional: true
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "300m"
                memory: "256Mi"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: x-likes-fetcher
  namespace: loom-dev
  labels:
    app: x-likes-fetcher
    component: data-ingestion
spec:
  # Run every 30 minutes
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: x-likes-fetcher
            component: data-ingestion
        spec:
          restartPolicy: Never
          containers:
          - name: x-likes-fetcher
            image: loom/x-likes-fetcher:latest
            imagePullPolicy: Never
            env:
            - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-infra-chart:9092"
            - name: LOOM_LOG_LEVEL
              value: "INFO"
            - name: X_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: x-credentials
                  key: bearer-token
                  optional: true
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "300m"
                memory: "256Mi"

---
# Deployment for scheduled consumers coordinator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduled-consumers
  namespace: loom-dev
  labels:
    app: scheduled-consumers
    component: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduled-consumers
  template:
    metadata:
      labels:
        app: scheduled-consumers
        component: data-processing
    spec:
      containers:
      - name: scheduled-consumers
        image: loom/scheduled-consumers:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: LOOM_LOG_LEVEL
          value: "INFO"
        - name: LOOM_ENVIRONMENT
          value: "development"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: scheduled-consumers
  namespace: loom-dev
  labels:
    app: scheduled-consumers
spec:
  selector:
    app: scheduled-consumers
  ports:
  - port: 8000
    targetPort: 8000
    name: http