apiVersion: v1
kind: Namespace
metadata:
  name: loom-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-monitor-api
  namespace: loom-dev
  labels:
    app: pipeline-monitor-api
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-monitor-api
  template:
    metadata:
      labels:
        app: pipeline-monitor-api
        component: monitoring
    spec:
      containers:
      - name: api
        image: loom/pipeline-monitor-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: LOOM_DATABASE_HOST
          value: "timescaledb"
        - name: LOOM_DATABASE_PORT
          value: "5432"
        - name: LOOM_DATABASE_NAME
          value: "loom"
        - name: LOOM_DATABASE_USER
          value: "loom"
        - name: LOOM_DATABASE_PASSWORD
          value: "loom"
        - name: CORS_ORIGIN
          value: "http://localhost:3000"
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "development"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-monitor-api
  namespace: loom-dev
  labels:
    app: pipeline-monitor-api
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: pipeline-monitor-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-monitor-frontend
  namespace: loom-dev
  labels:
    app: pipeline-monitor-frontend
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-monitor-frontend
  template:
    metadata:
      labels:
        app: pipeline-monitor-frontend
        component: monitoring
    spec:
      containers:
      - name: frontend
        image: loom/pipeline-monitor:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: VITE_API_URL
          value: "http://pipeline-monitor-api:8080"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-monitor-frontend
  namespace: loom-dev
  labels:
    app: pipeline-monitor-frontend
    component: monitoring
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30001
  selector:
    app: pipeline-monitor-frontend
