---
# Twitter OCR Processor Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-ocr-processor
  namespace: loom-dev
  labels:
    app: twitter-ocr-processor
    component: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-ocr-processor
  template:
    metadata:
      labels:
        app: twitter-ocr-processor
        component: data-processing
    spec:
      containers:
      - name: twitter-ocr-processor
        image: loom/twitter-ocr-processor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8008
          name: http
        env:
        - name: LOOM_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-infra-chart:9092"
        - name: DATABASE_URL
          value: "postgresql://loom:loom@postgres-chart:5432/loom"
        - name: MOONDREAM_OCR_URL
          value: "http://moondream-ocr:8007"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PORT
          value: "8008"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8008
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12  # Allow 2 minutes for startup
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8008
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8008
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: twitter-ocr-processor
  namespace: loom-dev
  labels:
    app: twitter-ocr-processor
spec:
  selector:
    app: twitter-ocr-processor
  ports:
  - port: 8008
    targetPort: 8008
    name: http