# Default values for kafka-infra Helm chart.
# This file contains a minimal but production-ready configuration that adheres to
# the workspace kubernetes standards (resource requests/limits, probes, security).
# Adjust as required per environment via values overrides.

kafka:
  replicas: 1
  image:
    repository: bitnami/kafka
    tag: 3.6.0-debian-11-r0
    pullPolicy: IfNotPresent
  config:
    # Example broker configuration
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
    KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
    KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
    # KRaft mode required configurations
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
    KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  storage:
    size: 1Gi
    storageClassName: hostpath
  listener:
    external:
      enabled: false  # Override to true with proper load balancer in production
    internal:
      port: 9092

zookeeper:
  enabled: false  # Enable if using ZooKeeper mode instead of KRaft
  replicas: 3
  image:
    repository: bitnami/zookeeper
    tag: 3.9.1-debian-11-r0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  storage:
    size: 5Gi
    storageClassName: standard

# Monitoring via JMX exporter sidecar
jmxExporter:
  enabled: false  # Disable for local development
  image:
    repository: bitnami/jmx-exporter
    tag: 0.21.0-debian-11-r0
  port: 5556

# Pod security context overrides
podSecurityContext: {}
containerSecurityContext: {}

# Node selector / tolerations / affinity
nodeSelector: {}
tolerations: []
affinity: {}

service:
  type: ClusterIP
  annotations: {}
