apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  # Placeholder for any additional configuration files
  # Currently using environment variables for configuration
