version: '3.8'

services:
  loom-macos-client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Loom API Configuration
      LOOM_API_BASE_URL: http://host.docker.internal:8000
      LOOM_DEVICE_ID: macos-docker-client
      
      # Logging
      LOOM_LOG_LEVEL: INFO
      
      # Data Collection Toggles
      LOOM_AUDIO_ENABLED: "true"
      LOOM_SCREEN_ENABLED: "true"
      LOOM_SYSTEM_ENABLED: "true"
      LOOM_LOCATION_ENABLED: "false"  # Typically disabled in containers
      LOOM_CLIPBOARD_ENABLED: "true"
      LOOM_APPS_ENABLED: "true"
      
      # Collection Intervals (seconds)
      LOOM_AUDIO_INTERVAL: "10"
      LOOM_SCREEN_INTERVAL: "30"
      LOOM_SYSTEM_INTERVAL: "60"
      LOOM_LOCATION_INTERVAL: "300"
      LOOM_CLIPBOARD_INTERVAL: "5"
      LOOM_APPS_INTERVAL: "10"
      
      # Audio Settings
      LOOM_AUDIO_SAMPLE_RATE: "44100"
      LOOM_AUDIO_CHANNELS: "1"
      LOOM_AUDIO_FORMAT: "wav"
      
      # Screen Settings
      LOOM_SCREEN_QUALITY: "80"
      LOOM_SCREEN_MAX_WIDTH: "1920"
      LOOM_SCREEN_MAX_HEIGHT: "1080"
      
      # Local API Server
      LOOM_SERVER_HOST: "0.0.0.0"
      LOOM_SERVER_PORT: "8080"
      
      # Storage
      LOOM_DATA_DIR: "/app/data"
      LOOM_LOG_DIR: "/app/logs"
      
      # Privacy Settings
      LOOM_EXCLUDE_SECURE_INPUT: "true"
      LOOM_EXCLUDE_PRIVATE_BROWSING: "true"
      LOOM_EXCLUDE_PASSWORDS: "true"
      
      # Timezone
      TZ: UTC
      DEBIAN_FRONTEND: noninteractive
      
    ports:
      - "8080:8080"  # Local API server
      
    volumes:
      - client_data:/app/data
      - client_logs:/app/logs
      
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  client_data:
  client_logs: