name: network_events_processing
description: Track WiFi connections and network environment changes
priority: low
data_volume:
  expected_events_per_second: 0.01  # Network changes are infrequent
  average_event_size_bytes: 500
  peak_multiplier: 10  # Burst when moving locations

stages:
  - name: database_writer
    service:
      name: kafka-to-db-saver
      image: loom/kafka-to-db-saver:latest
      replicas: 1
    input_topics:
      - device.network.wifi.raw
    output_topics: []
    configuration:
      batch_size: 50
      flush_interval_ms: 60000
      tables:
        - device_network_wifi_raw
      hypertable_config:
        time_column: timestamp
        chunk_time_interval: 7 days
        compression_after: 30 days
        retention_days: 90
    schema_mappings:
      input_schema: shared/schemas/device/network/wifi/v1.json
    processing:
      batch_size: 50
      timeout_seconds: 5
      retry_policy:
        max_retries: 5
        backoff_seconds: 2
    monitoring:
      sla_seconds: 0.1
      alert_on_error_rate: 0.01